# Generated by Django 4.2.6 on 2023-10-30 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="logo",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="logo",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="league",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="sports.league",
            ),
        ),
    ]
