# Generated by Django 4.2.6 on 2023-11-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sports", "0002_league_logo_team_logo_alter_team_league"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
