version: '3'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: abelcastrodev_dev_django
    command: /start
    volumes:
      - ./app/:/app/
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  postgres:
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile
    image: abelcastrodev_prod_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env


  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
