# Generated by Django 4.2.26 on 2026-04-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_normalize_tag_names_lowercase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
